=== swathisingamsetty12/ItemRestService/src/XSDS/Item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ItemList" 
xmlns:tns="http://www.example.org/ItemList" elementFormDefault="qualified">

<xs:element name="ItemList">
<xs:complexType>
  <xs:sequence>   
    <xs:element name="ItemInfo" type="tns:ItemInfo" maxOccurs="unbounded" minOccurs="1"/>
  </xs:sequence>
</xs:complexType> 
</xs:element>

<xs:complexType name="ItemInfo">
  <xs:sequence>
    <xs:element name="itemId" type="xs:string"/>
    <xs:element name="itemName" type="xs:string"/>
    <xs:element name="storeId" type="xs:string"/>
    <xs:element name="storeName" type="xs:string"/>    
    <xs:element name="price" type="xs:double"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="quantity" type="xs:integer"/>       
  </xs:sequence>
</xs:complexType> 

</xs:schema>

=== swathisingamsetty12/ItemRestService/src/SampleFiles/item6.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ItemList xmlns:tns="http://www.example.org/ItemList" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ItemList ../XSDS/Item.xsd ">
  <tns:ItemInfo>
    <tns:itemId>6</tns:itemId>
    <tns:itemName>top</tns:itemName>
    <tns:storeId>9001</tns:storeId>
    <tns:storeName>sunny</tns:storeName>
    <tns:price>30.0</tns:price>
    <tns:description>fv</tns:description>
    <tns:quantity>3</tns:quantity>
  </tns:ItemInfo>
</tns:ItemList>

=== swathisingamsetty12/ItemRestService/src/SampleFiles/Item.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ItemList xmlns:tns="http://www.example.org/ItemList" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ItemList ../XSDS/Item.xsd ">
  <tns:ItemInfo>
    <tns:itemId>tns:itemId</tns:itemId>
    <tns:itemName>tns:itemName</tns:itemName>
    <tns:storeId>tns:storeId</tns:storeId>
    <tns:storeName>tns:storeName</tns:storeName>
    <tns:price>0.0</tns:price>
    <tns:description>tns:description</tns:description>
    <tns:quantity>0</tns:quantity>
  </tns:ItemInfo>
</tns:ItemList>
